### PR TITLE
Add picojson to runtime dependencies and new upstream release 0.6.0

### PR DESCRIPTION
**Pull request by eaaltonen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.

I'm unsure of checklist item re-rendered.

This PR:
* adds `picojson` to the runtime dependencies so that it's automatically installed with `conda`. In most cases users probably want this.
* Updates to new upstream release 0.6.0

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@eaaltonen, thanks for this! Any chance I can convince you to add yourself as a maintainer of this recipe? You seen to know more about jwt-cpp than I do (which wouldn't be hard, I'm just here because scitokens-cpp needs jwt-cpp and I need scitokens-cpp)...

**Comment by eaaltonen** [comment]
@duncanmmacleod, np.

> I'm just here because scitokens-cpp needs jwt-cpp and I need scitokens-cpp

I'm actually here for very similar reasons and my knowledge of jwt-cpp isn't more in depth than noticing "why does this not compile" and then checking the release notes :)

I am willing to try being a co-maintainer on jwt-cpp. Conda seems very promising and it'd probably be a good learning experience.

If I find the time, I might to try to build [variants](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html), since our company needs to test against OpenSSL 1.1.1 (_on Ubuntu 20.04_) for at least a little while.

**Comment by duncanmmacleod** [comment]
> I am willing to try being a co-maintainer on jwt-cpp. Conda seems very promising and it'd probably be a good learning experience.

Excellent, please add your github username below mine at the bottom of the `meta.yaml` file. Once merged the conda-forge bots will take care of adding you to the relevant groups/teams.

**Comment by eaaltonen** [comment]
@duncanmmacleod : I updated the `recipe-maintainers` list. Was there anything else?

**Comment by duncanmmacleod** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
